### ISSUE TITLE
Removed all previously created templates without warning

### ISSUE THREAD

**Issue by jepsonrob** [umbraco/The-Starter-Kit#48]
It feels like it would be a good idea to give some kind of warning that installing this will remove all previous templates, because for people like myself that live dangerously and sometimes don't use version control it's a bit upsetting to have everything deleted!

**Comment by nul800sebastiaan** [comment]
Sorry for the (very) late reply 🙈

There's nothing in the starter kit that would delete existing templates but it will overwrite them when you install this. This is expected behavior. What would be great during installation of a package is if we look at the files in the package and the files on disk and make sure that if anything already exists we list it as a warning before we overwrite anything.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by UnsungHeros** [comment]
Uninstalling the starter kit might delete 'existing' templates though.  So I can see where it appears that the content was deleted.  

So I suppose the options are either expect the package developers to check all the document types, or have Umbraco core check the Document Types before installing and present a warning.   In the case of the former, there is no action needed and those installing packages need to be responsible to thoroughly test the packages they install.  I guess it will highly depend on the use case.  

If the expectation is for non-developers to be able to install a package and go, then there would have to be a standardized way to identify all document types, templates, and maybe other elements being installed and warning if they already exist.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
